
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://www.robertkraner.at"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

  #baseurl: /

# Google tracking id

# google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "de"
author: "Robert Kraner"
title: "Robert Kraner"
description: "Persönliche Website des Autors und Schriftstellers Robert Kraner."
keywords: "autor, robert kraner, valerie, weißdorn, kreide, österreich, schriftsteller, literatur, literat, waldviertel"
address: "Sonnleite 7"
zipcode: "A-3902 Vitis"
mobilephone: "+43(0)676/39 24 858"

# favicon: "/img/favicon.ico"

################
# Header layout #
################

  # black-favicon: "/img/Iconsmind-Outline-Pen.ico"
  #logo: "" # leave blank if you don't want a logo

background-img: "../img/banner.webp"
# background-img: "../img/Robert_Kraner.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 40
start-delay: 500
delete-delay: 2000
lines: # You can add HTML Tags in the Text
  - text: "Ein freier Platz"
  - text: "Auf Papier ist vonnöten"
  - text: "Eine Feder"
  - text: "Ein Hut"
  - text: "Eine Lage Frost"
  - text: "Ein Herz über dem Staub"

#me-img: "/img/jetpacktocat.png"
me-img: "/img/author.webp"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

# disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "mail@robertkraner.at"


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
# author_blurb: "Robert Kraner ist Schriftgelehrter und mag Blumen."
# author_blurb_image: "/img/author.webp"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/robert.kraner.1958"
  - title: "rss"
    url: "feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Über: 'about'
  Bücher: 'buecher'
  Publikationen: 'publikationen'
  Aktuelles: 'last-posts'
#  Timeline: 'timeline'
  Links: 'links'
  Kontakt: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]
include: [".htaccess"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
