name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
      # for github-pages
      #    - name: GitHub Modifications
      #      run: |
      #        echo "baseurl: /robertkraner.at" >> _config.yml
      
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
          
    - name: Deploy to World4You
      if: success()
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        server-dir: webroot/
        local-dir: _site/
        exclude: "[stats]"

          #    - name: Deploy to GitHub Pages
          #      if: success()
          #      uses: crazy-max/ghaction-github-pages@v2
          #      with:
          #        target_branch: gh-pages
          #        build_dir: _site
          #      env:
          #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
